### ISSUE TITLE
no response from gateway..

### ISSUE THREAD

**Issue by halukmy** [fcgdam/TTGO_LoRa32#2]
Sending uplink packet...
EV_TXCOMPLETE (includes waiting for RX windows)
Sending uplink packet...
EV_TXCOMPLETE (includes waiting for RX windows)

i am not seee any recieve..

any update?

**Comment by fcgdam** [comment]
Your node can reach the gateway (maybe), but the GW can't reach your node...

**Comment by halukmy** [comment]
how can i send command to lorawan node via turn on light off light or anything? is it not possible?

**Comment by fcgdam** [comment]
The main use case domain for Lora is not bidirectional communication. 
Still, yes it is possible, but the gateway must be close in the vicinity.

**Comment by halukmy** [comment]
@fcgdam can you share example?

i make bi comminicate on my own network so yes it can but hows possible on gateway look so hard
