### ISSUE TITLE
do you have got Class-C Node unit ? (like lmic)

### ISSUE THREAD

**Issue by halukmy** [fcgdam/TTGO_LoRa32#4]
hello, i been searching class-c for control city units but all examples are on arduino for class-a

is there any support for class-C?

**Comment by fcgdam** [comment]
Don't take me wrong, but please use only this for issues related with the code, not for generic support...

All nodes support class C, but on the other hand, the LMIC code and the back-end code to support Class C is another thing... As I'm aware, there are some implementations for Class C but not for LMIC or for the Things Network, as Borroz as answered you.
