### ISSUE TITLE
Which SSD1306 library to use?

### ISSUE THREAD

**Issue by jbrepogmailcom** [fcgdam/TTGO_LoRa32#8]
There are several libraries for SSD1306, one even named ssd1306. But this one does not work, which is the correct one? From what author? Thank you.

**Comment by fcgdam** [comment]
This means that your hardware is different from the one that I've used that has a SSD1306.

Maybe your chip is the ssd1106?  It's is a cheaper version of the SSD1306. Not sure what lib should use for this one, maybe Adafruit's?

**Comment by jbrepogmailcom** [comment]
The chip is ESP32-based TTGO LoRa32. I have installed all libraries that contained SSD1306 (there are about 10 of them) and it finally compiled without complaints
